import type { Metadata } from 'next'
import { RootLayout } from '@payloadcms/next/layouts'
import React from 'react'
import './custom.scss'
import { importMap } from './admin/importMap.js'
import config from '../../src/payload.config'

type Args = {
  children: React.ReactNode
}

const Layout = ({ children }: Args): React.ReactElement => (
  <RootLayout 
    config={config} 
    importMap={importMap}
    serverFunction={undefined}
  >
    {children}
  </RootLayout>
)

export default Layout

export const metadata: Metadata = {
  title: 'Payload Admin',
  description: 'Generated by Payload',
  openGraph: {
    title: 'Payload Admin',
    description: 'Generated by Payload',
  },
}
